### ISSUE TITLE
Updates to AnnotationList

### ISSUE THREAD

**Issue by holtgrewe** [charite/jannovar#143]
* rename to VariantAnnotations
* add GenomeChange
* remove List interface

**Comment by julesjacobsen** [comment]
From our discussion on HipChat:

Currently the way you end up constructing your AnnotationList is inconsistent with what the AnnotationList constructor says it needs. You actually start from the GenomeChange, not the Collection<Annotation>.

e.g. in VariantAnnotator
```
public AnnotationList buildAnnotationList(GenomeChange change) throws AnnotationException {

public AnnotationList buildAnnotationList(int chr, int position, String ref, String alt, PositionType posType)
```
despite the AnnotationList constructor just requiring the annotations:
```
public AnnotationList(Collection<Annotation> entries)
```

The contructor really ought to be:
```
public VariantAnnotations(GenomeChange change, Collection<Annotation> entries)
```
as this better reflects it's actual behaviour. This way the VariantAnnotator produces VariantAnnotations, rather than AnnotationLists which seems far more logical. 

Changing AnnotationList to VariantAnnotations implement VariantDescription and add GenomeChange to the top level. Add a getAnnotations method too!

If we have a top-level GenomeChange in the VariantAnnotations, this would have to be the canonical + strand.
Each Annotation would still need their own GenomeChanges as they could have come from a different strand in the case of two overlapping genes transcribed from different strands.

**Comment by holtgrewe** [comment]
@julesjacobsen could you validate my PR #163 and look whether I forgot anything?
