### ISSUE TITLE
Review A/I prefixes

### ISSUE THREAD

**Issue by holtgrewe** [charite/jannovar#152]
As far as I can see, the only place where A and I prefixes for abstract and interface is the pedigree module.

I think we should resolve this in favour of consistency with the rest of Jannovar.

What do you think, @visze

**Comment by holtgrewe** [comment]
Also, I am not so certain about putting the `runSingleCase()` and `runMultipleCase()` into an interface since this is an implementation detail and not part of the public interface.

**Comment by visze** [comment]
Well I for interface and A for abstact is my personal writing (I learned it this way at the university and kept it.
For me in Jannovar it doesn't matter if we use this or not.

 `runSingleCase()` and `runMultipleCase()` have to be in the interface. Otherwise they cannot be used in the Abstact class without implementing them. I just wanted to put the run method into the abstarct class
