### ISSUE TITLE
Bug in MendelianCheckerXRHom

### ISSUE THREAD

**Issue by pnrobinson** [charite/jannovar#363]
private boolean parentsAreCompatible(GenotypeCalls calls) {
final ImmutableSet<String> femaleParentNames = queryDecorator.getAffectedFemaleParentNames();
final ImmutableSet<String> maleParentNames = queryDecorator.getAffectedFemaleParentNames();

In this method the wrong function is chosen to get the maleParentNames.

**Comment by visze** [comment]
Thx for finding that. I took a closer look and it seems that the wrongly written function had no effect at all.

1 ) Does this error filters out correct variants from affected females because the parents were treated as parent of affected mails?
  -> No! The checks in second part (when it checks the maleParentNames) are included in the first part. So it failed within the  femaleParentNames .
2) The actual (wrong) code does not consider parents of male affected. Is this a problem here?
 -> No. This is because of the really specific check made here. This check is if the variant is correctly inherited from BOTH parents resulting in a HOM or HEMI mutation in the child. This is clear for females because both parents have to have the mutation. So every parent of affected males shoudl have the variant at least as HET or HEMI. When we are looking for "HOM" in affected males (which will be of course "HEMI") we cannot check anything because it can be inherited from the father OR the mother. At this point we do not check a trio. We check all parents and do not know which belong together. This means that we can remove any "parents of affected males" check

I will remove the wrongly written code and make a pull request. Will not change anything in test etc.

**Comment by visze** [comment]
closed through PR #366
