### ISSUE TITLE
Jannovar annotates a conflicting variant effect

### ISSUE THREAD

**Issue by stolpeo** [charite/jannovar#368]
Jannovar annotates a conflicting variant effect: `start_lost&synonymous_variant`.

VEP using RefSeq classifies this variant as `start_lost`, `5_prime_UTR_variant`, `regulatory_region_variant` using the RefSeq transcripts.

```
2      220462640       rs681747    G       T       4143.90 MaxFreqAd;MaxFreqAr     AC=6;AF=1.00;AN=6;ANN=T|start_lost&synonymous_variant|HIGH|STK11IP|114790|transcript|NM_052902.2|Coding|1/25|c.2T>T|p.0?|45/18578|2/3300|1/1100||WARNING_REF_DOES_NOT_MATCH_TRANSCRIPT
```

**Comment by visze** [comment]
Can you post the transcripts of vep with the corresponding annotation?

Am 14.11.2017 09:53 schrieb "Oliver" <notifications@github.com>:

**Comment by stolpeo** [comment]
```
start_lost | HIGH | STK11IP | 114790 | Transcript | NM_052902.2
5_prime_UTR_variant | MODIFIER | STK11IP | 114790 | Transcript | NM_052902.3
5_prime_UTR_variant | MODIFIER | STK11IP | 114790 | Transcript | XM_005246262.1
regulatory_region_variant | MODIFIER | - | - | RegulatoryFeature | ENSR00000130580
```

Is this information sufficient?

**Comment by visze** [comment]
we  investigated this further and the difference between VEP and Jannovar is that one specific transcript is not present in Jannovar and @stolpeo forgott to print ALL effects with jannovar not the most tempting one.

But now the interesting question is, why we have the class `start_lost` AND `synonymous_variant` for ONE transcript!

Is this because we have the error: `WARNING_REF_DOES_NOT_MATCH_TRANSCRIPT`

@holtgrewe can you help here?

**Comment by visze** [comment]
OK this annotation is strange but correct!

The problem is, that the reference has at this position a G! The RefSeq transcript has at this position a T. So from a transcript point of view we do not have any variant. That's why Jannovar calls a `synonymous_variant`. From the reference Point it is a `start_lost`. So the warning `WARNING_REF_DOES_NOT_MATCH_TRANSCRIPT` should taken to be serious.

To check it on your own just open the mutalyzer links here:
[NM_052902.2:c.2T>T](https://mutalyzer.nl/name-checker?description=NM_052902.2%3Ac.2T%3ET)
[NM_052902.2:c.2G>T](https://mutalyzer.nl/name-checker?description=NM_052902.2%3Ac.2G%3ET)
