### ISSUE TITLE
function naming in transcript model

### ISSUE THREAD

**Issue by iimpulse** [charite/jannovar#466]
jannovar-core/src/main/java/de/charite/compbio/jannovar/reference/TranscriptModel.java#126

The function name doesn't make sense english wise. Please consider "hasSubstitution", removing "is".

**Comment by visze** [comment]
yes this makes no sense in english but we are using a naming convention and therefore it is correct.

The helper function `isHasSubstitutions` returns the variable `hasSubstitution` and because it is a boolean it starts with `is`. For example if the variable `hasSubstitution` returns a String or a List the helper function will start with `get`. It looks maybe wired but there is a logic behind.
