### ISSUE TITLE
Release Notes

### ISSUE THREAD

**Issue by iimpulse** [charite/jannovar#467]
Is there a place to review release notes for jannovar? It looks like classes are changing, and this is an integral part of my current application. It would be nice to know what broad overall changes happened so I could adjust accordingly.

**Comment by visze** [comment]
We are happy to hear that you use jannovar in your application. We try to log everything in the [CHANGELOG.md](https://github.com/charite/jannovar/blob/master/CHANGELOG.md) file since Jannovar v0.13. The history should also be accessible via the [documentation](https://doc-openbio.readthedocs.io/projects/jannovar/en/latest/history.html)

Since we have a jannovar version smaller than 1 we will not use semantic versioning. After the major 1.0 release we will strictly stick to semantic versioning. But the main jannovar-core module is extremely stable and we will try to avoid doing changes here. (and if we do we will document them!)
