### ISSUE TITLE
Step by step procedure

### ISSUE THREAD

**Issue by KarthickRajaNarayanan** [charite/jannovar#496]
Hi,

Where can i get the protocol/procedure to use this tool for my data set for variant annotation?

Regards,
Karthick

**Comment by visze** [comment]
Hi Karthick,

thank you for your interest in Jannovar. Did you had a look at the documentation: https://jannovar.readthedocs.org. Maybe the short Quickstart will be the best to start using Jannovar.

just a side mark: we have right now problems with the refseq database. maybe you have to replace it with ensembl.

Best,
Max

**Comment by KarthickRajaNarayanan** [comment]
Hi Max,

Thanks a lot for your input!

What is the command line for downloading ref genome from ENSEMBL? 

Regards,
Karthick

**Comment by visze** [comment]
Hi Karthick,

Have a look at the "downloading transcript-db" documentation here: https://doc-openbio.readthedocs.io/projects/jannovar/en/master/download.html

We recogniced that the download links are broken (one major issue, because websites like to change theor links). So you might get errors when downloading the transcript databases. We already fixed the issue in the development branch. So you can install janovar from source following this: https://doc-openbio.readthedocs.io/projects/jannovar/en/master/install.html#install-from-source

One additional command is needed: after `Development # cd jannovar` switch to the development branch `Development # git checkout develop`.

The easy-to-use conda version is not ready jet and we need to make a new release. Hope this will happen in th enext week.

Best,
Mac

**Comment by KarthickRajaNarayanan** [comment]
Sure! Thanks a lot! Max.

Regards,
Karthick
