### ISSUE TITLE
Consider sorted lists instead of an interval tree data structure

### ISSUE THREAD

**Issue by holtgrewe** [charite/jannovar#51]
Would be simpler and tentatively faster.

There is no need to maintain a tree if we do not have dynamic rebalancing (which the tree does not support anyway).

**Comment by pnrobinson** [comment]
the interval tree makes the search a lot faster, a sorted list would not work as well because of overlaps


Dr. med. Peter N. Robinson, MSc.
Professor of Medical Genomics
Professor in the Bioinformatics Division of the Department of Mathematics and Computer Science of the Freie Universität Berlin
Institut für Medizinische Genetik und Humangenetik
Charité - Universitätsmedizin Berlin
Augustenburger Platz 1
13353 Berlin
Germany
+4930 450566006
Mobile: 0160 93769872
peter.robinson@charite.de
http://compbio.charite.de
http://www.human-phenotype-ontology.org
Introduction to Bio-Ontologies: http://www.crcpress.com/product/isbn/9781439836651
I have learned from my mistakes, and I am sure I can repeat them exactly
ORCID ID:http://orcid.org/0000-0002-0736-9199
Scopus Author ID 7403719646
Appointment request: http://doodle.com/pnrobinson
________________________________________
Von: Manuel Holtgrewe [notifications@github.com]
Gesendet: Mittwoch, 7. Januar 2015 15:23
An: charite/jannovar
Betreff: [jannovar] Consider sorted lists instead of an interval tree data structure (#51)

Would be simpler and tentatively faster.

There is no need to maintain a tree if we do not have dynamic rebalancing (which the tree does not support anyway).

**Comment by holtgrewe** [comment]
I agree, my idea is to use a `ArrayList` representation of a binary tree as described here:

http://en.wikipedia.org/wiki/Interval_tree#Augmented_tree

**Comment by pnrobinson** [comment]
Lass uns drüber reden. Ein Intervalltree ist viel mehr als ein binary baum! Aber vielleicht geht es auch…aber; if it anit broke, don’t fix it, was ist denn kaputt?

Dr. med. Peter N. Robinson, MSc.
Professor of Medical Genomics
Institut für Medizinische Genetik und Humangenetik
Charité - Universitätsmedizin Berlin
Augustenburger Platz 1
13353 Berlin
Germany
+4930 450566006
Mobile: 0160 93769872
peter.robinson@charite.de
http://compbio.charite.de
http://www.human-phenotype-ontology.org
Introduction to Bio-Ontologies: http://www.crcpress.com/product/isbn/9781439836651

Von: Manuel Holtgrewe [mailto:notifications@github.com]
Gesendet: Mittwoch, 7. Januar 2015 18:21
An: charite/jannovar
Cc: Robinson, Peter
Betreff: Re: [jannovar] Consider sorted lists instead of an interval tree data structure (#51)


I agree, my idea is to use a ArrayList representation of a binary tree as described here:

http://en.wikipedia.org/wiki/Interval_tree#Augmented_tree
